name = "home"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-01-01"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".svelte-kit/cloudflare"

[build]
command = "npm run build"

# Routes are optional - only needed if you have a custom domain
# [[routes]]
# pattern = "yourdomain.com/*"
# zone_name = "yourdomain.com"