name = "home"
compatibility_date = "2024-01-01"

# This is a Pages project with Functions
pages_build_output_dir = ".svelte-kit/cloudflare"

# Enable Node.js compatibility for Pages Functions
compatibility_flags = ["nodejs_compat"]