name = "home"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

[site]
bucket = ".svelte-kit/cloudflare"

[build]
command = "npm run build"

compatibility_flags = ["nodejs_compat"]