# Cloudflare Pages configuration
# This file is used when deploying with wrangler CLI
# The GitHub Action uses cloudflare/pages-action which handles this differently

name = "home"
compatibility_date = "2024-01-01"

# For direct wrangler CLI deployment
[assets]
directory = "./build"
