# This file is optional for Cloudflare Pages
# It's mainly used for additional configuration

name = "home"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "build"

# Pages Functions (optional)
# [[pages.functions]]
# directory = "src/routes/api"
