name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Build Storybook
        run: npm run build-storybook
      
      - name: Create Release Archive
        run: |
          tar -czf build-${{ github.ref_name }}.tar.gz build/
          tar -czf storybook-${{ github.ref_name }}.tar.gz storybook-static/
      
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ## Changes in this Release
            ${{ steps.changelog.outputs.changelog }}
          files: |
            build-${{ github.ref_name }}.tar.gz
            storybook-${{ github.ref_name }}.tar.gz
          draft: false
          prerelease: false